project:
  type: website

website:
  title: "Dungeon Magic: Gift of the Magi"
  navbar:
    search: true
    
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Tutorials"
        contents:

      - section: "How-To"
        contents:

      - section: "Fundamentals"
        contents:

      - section: "Reference"
        contents:
          - ./reference/definitions.qmd
          - ./reference/cart_data.qmd

format:
  html:
    theme: flatly
    mainfont: "Segoe UI Emoji"
    fontsize: 12pt
    css: styles.css
    toc: true




    